/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT Lab6F28335Project.cdb */

/*  Include Header File  */
#include "Lab6F28335Projectcfg.h"

/*  Config Structures */
/*  Handles  */
