/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT gigous_bkuo_lab6.cdb */

/*  Include Header File  */
#include "gigous_bkuo_lab6cfg.h"

/*  Config Structures */
/*  Handles  */
