/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT gigous_kuo_lab8.cdb */

/*  Include Header File  */
#include "gigous_kuo_lab8cfg.h"

/*  Config Structures */
/*  Handles  */
